# numpy
-

In [47]:
import numpy as np
list=[1,2,3,4,5,6,7,8,9,]
li=np.array(list)
li[2:4]


array([3, 4])

In [25]:
#vectorized operations
li*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [26]:
li/2

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [27]:
li.size

9

In [31]:
li.ndim

1

In [39]:
#using numpy a range we can create list

arr1=np.arange(20)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [41]:
#2d array

array2=[[1,2,3],[11,22,33],[111,222,333]]
arr2=np.array(array2)
arr2

array([[  1,   2,   3],
       [ 11,  22,  33],
       [111, 222, 333]])

In [80]:
arr2[1,2:3] #this is one dimension aray because of 1st index

array([33])

In [60]:
arr2d=np.arange(36).reshape(4,9)
arr2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [61]:
arr2d[2:3,2:5] #for slicing you need to give the 4 values or : is compulsary for both values

array([[20, 21, 22]])

In [62]:
arr2d[1:3,5:7]

array([[14, 15],
       [23, 24]])

In [67]:
arr2d[0:,6:]

array([[ 6,  7,  8],
       [15, 16, 17],
       [24, 25, 26],
       [33, 34, 35]])

# fancy indexing

In [68]:
arr2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [69]:
arr2d[:,[5,8,0,3]]

array([[ 5,  8,  0,  3],
       [14, 17,  9, 12],
       [23, 26, 18, 21],
       [32, 35, 27, 30]])

In [81]:
arr2d[[1,3],:5]

array([[ 9, 10, 11, 12, 13],
       [27, 28, 29, 30, 31]])

In [77]:
arr2d[[1,2],[3,5]]

array([12, 23])

In [82]:
arr2d[:,::2]

array([[ 0,  2,  4,  6,  8],
       [ 9, 11, 13, 15, 17],
       [18, 20, 22, 24, 26],
       [27, 29, 31, 33, 35]])

In [83]:
arr2d[:,::-2]

array([[ 8,  6,  4,  2,  0],
       [17, 15, 13, 11,  9],
       [26, 24, 22, 20, 18],
       [35, 33, 31, 29, 27]])

In [87]:
arr3d=np.arange(64).reshape(4,4,4)

In [205]:
arr3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [123]:
arr3d[:,2:3,1:3]

array([[[ 9, 10]],

       [[25, 26]],

       [[41, 42]],

       [[57, 58]]])

In [124]:
a=np.random.randn(4,4)

In [125]:
a

array([[-0.44415177, -2.34009148,  1.04412446,  2.57742047],
       [ 0.30604826,  1.68675561,  0.63297834, -0.08169327],
       [-0.613453  , -0.50134753,  0.06771418,  0.87991665],
       [-0.54104102,  0.21459313, -0.1148315 , -0.40961966]])

In [126]:
b=np.random.randn(4,4)

In [127]:
b

array([[ 1.40190346,  0.08682056,  0.84589132,  0.00540464],
       [-2.53545744, -0.52204366,  0.35382032, -1.01416346],
       [ 0.27165199,  0.65688957, -1.57492444,  1.43323983],
       [ 0.45189211, -0.84200357, -0.04469738, -0.31582314]])

In [149]:
a+b

array([[ 0.95775169, -2.25327092,  1.89001577,  2.58282511],
       [-2.22940917,  1.16471195,  0.98679866, -1.09585673],
       [-0.341801  ,  0.15554204, -1.50721026,  2.31315648],
       [-0.08914891, -0.62741044, -0.15952888, -0.7254428 ]])

In [129]:
a@b #@ is used for matrix multiplication

array([[ 6.75889889, -0.30125434, -2.96329712,  3.05330651],
       [-3.71261366, -0.3694059 , -0.13754962, -0.77598142],
       [ 0.82716552, -0.48794725, -0.8422762 ,  0.32428547],
       [-1.51887713,  0.11046913, -0.18257463, -0.25577036]])

In [136]:
a1=np.arange(20).reshape(4,5)
a1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [137]:
a2=np.arange(25).reshape(5,5)
a2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [135]:
a1@a2

array([[ 150,  160,  170,  180,  190],
       [ 400,  435,  470,  505,  540],
       [ 650,  710,  770,  830,  890],
       [ 900,  985, 1070, 1155, 1240]])

In [141]:
np.ones_like(a1)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [145]:
np.linspace(1,35,22) #break value in given point

array([ 1.        ,  2.61904762,  4.23809524,  5.85714286,  7.47619048,
        9.0952381 , 10.71428571, 12.33333333, 13.95238095, 15.57142857,
       17.19047619, 18.80952381, 20.42857143, 22.04761905, 23.66666667,
       25.28571429, 26.9047619 , 28.52380952, 30.14285714, 31.76190476,
       33.38095238, 35.        ])

In [156]:
list=np.array([1,2,3,4,5,6,7,8,9,])
list>5

array([False, False, False, False, False,  True,  True,  True,  True])

In [170]:
list>5

TypeError: '>' not supported between instances of 'list' and 'int'

In [171]:
#list[list>5]

In [174]:
list=np.array([1,2,3,4,5,6,7,8,9,])
a=[True,False,True,False,True,False,True,False,True,False]
list[a]

IndexError: boolean index did not match indexed array along dimension 0; dimension is 9 but corresponding boolean dimension is 10

In [182]:
arr2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [183]:
arr2d[arr2d>10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30, 31, 32, 33, 34, 35])

In [194]:
arr2d [(arr2d>10) & (arr2d<250)]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30, 31, 32, 33, 34, 35])

In [213]:
array3=arr3d.ravel()#make a copy but change value in original one

In [216]:
array3[20:40]=100

In [217]:
array3

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63])

In [225]:
arr3d

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11],
        [ 12,  13,  14,  15]],

       [[ 16,  17,  18,  19],
        [100, 100, 100, 100],
        [100, 100, 100, 100],
        [100, 100, 100, 100]],

       [[100, 100, 100, 100],
        [100, 100, 100, 100],
        [ 40,  41,  42,  43],
        [ 44,  45,  46,  47]],

       [[ 48,  49,  50,  51],
        [ 52,  53,  54,  55],
        [ 56,  57,  58,  59],
        [ 60,  61,  62,  63]]])

In [226]:
arr3d.flatten()#make copy and not change in original one

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63])

In [227]:
arr3d.reshape(64) #work like ravel

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63])

In [228]:
arr3d

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11],
        [ 12,  13,  14,  15]],

       [[ 16,  17,  18,  19],
        [100, 100, 100, 100],
        [100, 100, 100, 100],
        [100, 100, 100, 100]],

       [[100, 100, 100, 100],
        [100, 100, 100, 100],
        [ 40,  41,  42,  43],
        [ 44,  45,  46,  47]],

       [[ 48,  49,  50,  51],
        [ 52,  53,  54,  55],
        [ 56,  57,  58,  59],
        [ 60,  61,  62,  63]]])

# concatenation of arrays

In [258]:
arr2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [259]:
array2d1=arr2d[:]*2
array2d1

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16],
       [18, 20, 22, 24, 26, 28, 30, 32, 34],
       [36, 38, 40, 42, 44, 46, 48, 50, 52],
       [54, 56, 58, 60, 62, 64, 66, 68, 70]])

In [260]:
array2d1=np.concatenate([arr2d,array2d1],axis=1)#axis define to write in rows or column its only 0 and 1

In [261]:
array2d1

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  0,  2,  4,  6,  8, 10, 12,
        14, 16],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 20, 22, 24, 26, 28, 30,
        32, 34],
       [18, 19, 20, 21, 22, 23, 24, 25, 26, 36, 38, 40, 42, 44, 46, 48,
        50, 52],
       [27, 28, 29, 30, 31, 32, 33, 34, 35, 54, 56, 58, 60, 62, 64, 66,
        68, 70]])

In [262]:
arr2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [266]:
np.split(arr2d,3,axis=1)#axis 1 do vertically split in equal parts

[array([[ 0,  1,  2],
        [ 9, 10, 11],
        [18, 19, 20],
        [27, 28, 29]]),
 array([[ 3,  4,  5],
        [12, 13, 14],
        [21, 22, 23],
        [30, 31, 32]]),
 array([[ 6,  7,  8],
        [15, 16, 17],
        [24, 25, 26],
        [33, 34, 35]])]

In [267]:
np.split(arr2d,2,axis=0)#axis 0 split in horizontally in equal parts

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17]]),
 array([[18, 19, 20, 21, 22, 23, 24, 25, 26],
        [27, 28, 29, 30, 31, 32, 33, 34, 35]])]

# broadcasting

In [277]:
baray=np.arange(12).reshape(3,4)

In [278]:
baray

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [279]:
caray=np.arange(3).reshape(3,1)

In [280]:
caray

array([[0],
       [1],
       [2]])

In [281]:
baray+caray

array([[ 0,  1,  2,  3],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13]])

In [288]:
x=np.array([[1],[2],[3]])
y=np.array([4,5,6])
h=np.broadcast(x,y)

In [289]:
h

# pandas
  -series
  
  -data frame

In [310]:
import pandas as pd

In [321]:
s1=pd.Series(['nasir','nabeel','nayyar','farhan'])
s1

0     nasir
1    nabeel
2    nayyar
3    farhan
dtype: object

In [322]:
s1[2]

'nayyar'

In [324]:
s1.loc[1:3]

1    nabeel
2    nayyar
3    farhan
dtype: object